import Head from "next/head";
import { Inter } from "next/font/google";
import Hero from "@/components/Hero";
import About from "@/components/About";
import Curriculum from "@/components/Curriculum";
import aboutpic from "../../public/assets/About pic.jpg"
import outcomepic from "../../public/assets/Outcome pic.jpg"
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Panaverse DAO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />

        <About 
        title = "Web3 & Metaverse"
        text= "In this brand-new type of curriculum, students will learn how to make money and boost exports in the classroom and will begin doing so within six months of the program's beginning. It resembles across between a corporate venture and an educational project." 
        btntext = "See Curriculum"
        btnlink = "#currciulum"
        target = "_self"
        pic = {aboutpic}
        />

        <Curriculum />

        <About
        title = "Top Outcomes For Participants"
        text = "The graduates of this program will own products that are marketed globally by the Panaverse DAO and, and will also be able to make more $96,000/year by offering services. This would give Pakistani professionals and students a fantastic opportunity to better their financial situation while also giving the economy a much-needed boost by expanding software exports."
        btntext = "Join Now"
        btnlink = "https://www.piaic.org"
        target = "_blank"
        pic = {outcomepic}
        />

      </main>
    </>
  );
}
